### PR TITLE
Interface number - Fixes #382

### LINKED ISSUE #382: NetAdapterName: InterfaceNumber and InterfaceIndex doesn't seem to be working
System.InvalidOperationException: A network adapter matching the parameters was not found. Please correct the properties and try again. 

#### Details of the scenario you tried and the problem that is occurring
Doesn't seem to find the adapter based off the filter. Looking at the Find-Adapter function, I show:

VERBOSE: Find-NetworkAdapter: Finding network adapters matching the parameters.
VERBOSE: Find-NetworkAdapter: Found all network adapters because no filter parameters provided.
VERBOSE: Find-NetworkAdapter: 2 network adapters were found matching the parameters.
System.InvalidOperationException: Please adjust the parameters or specify IgnoreMultipleMatchingAdapters to only use the first and try again.

Looking at the code https://github.com/PowerShell/NetworkingDsc/blob/3db6d5ea444ee60ca4ffd8fd4e134763cd070e08/Modules/NetworkingDsc.Common/NetworkingDsc.Common.psm1#L235

And it appears you need the parameter IgnoreMultipleMatchingAdapters to be true and you need to specify the adapter number. 

`Find-NetworkAdapter -InterfaceNumber 1 -IgnoreMultipleMatchingAdapters $true -verbose `
 
#### Suggested solution to the issue
Not sure what this variable would be used for to be honest, so can't provide a solution

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```        NetAdapterName RenameNetAdapterPrivate {
            NewName           = 'Private'
            DriverDescription = 'Hyper-V Virtual Ethernet Adapter'
            InterfaceNumber   = 1
        }
```
```        NetAdapterName RenameNetAdapterPrivate {
            NewName           = 'Private'
            DriverDescription = 'Hyper-V Virtual Ethernet Adapter'
            InterfaceIndex   = 4
        }
```

#### The operating system the target node is running
OsName               : Microsoft Windows Server 2016 Standard
OsOperatingSystemSKU : StandardServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 14393.2828.amd64fre.rs1_release_inmarket.190216-1457
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version and build of PowerShell the target node is running
Name                           Value                                                                                                 
----                           -----                                                                                                 
PSVersion                      5.1.14393.2828                                                                                        
PSEdition                      Desktop                                                                                               
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                               
BuildVersion                   10.0.14393.2828                                                                                       
CLRVersion                     4.0.30319.42000                                                                                       
WSManStackVersion              3.0                                                                                                   
PSRemotingProtocolVersion      2.3                                                                                                   
SerializationVersion           1.1.0.1  

#### Version of the DSC module that was used ('dev' if using current dev branch)
NetAdapterName            NetworkingDsc                  7.0.0.0

### PR DESCRIPTION
**Pull request by Outek**
#### Pull Request (PR) description

Fixed Network Adapter renaming

#### This Pull Request (PR) fixes the following issues
- Fixes #382 

#### Task list
- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md in resource folder.
- [ ] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/networkingdsc/424)

### CODE REVIEW

**Comment by PlagueHO** [comment]
It looks like this tests are failing @Outek

**Comment by Outek** [comment]
Yes i know @PlagueHO , if i run the unit tests locally everything is green...

**Comment by PlagueHO** [comment]
Hi @Outek - can you rebase this onto the latest upstream Dev commit? It should fix the style issues. I'll then take a look at the other test failures.

**Comment by PlagueHO** [comment]
Sorry @Outek - looks like I missed this repo when we were correcting the hashtable format. So I'm going to submit a PR to fix that.

**Comment by PlagueHO** [comment]
Hi @Outek - I've fixed the issues with the Hashtable format, so you should be able to rebase onto Dev and resolve the conflicts which should fix the CI failures. I'll then review. Sorry about the delay.

**Comment by PlagueHO** [comment]
Hi @Outek - are you still keen to complete this?

**Comment by Outek** [comment]
I think i have to start over, i deleted my Fork.

**Pull request closed without merging**
