### PR TITLE
DnsServerAddress: fixes #446, simplified SET, validation error handling

### LINKED ISSUE #446: DnsServerAddress: Test-TargetResource always returns $false
#### Details of the scenario you tried and the problem that is occurring

I have a configuration that contains the DnsServerAddress resource, where I specify that DNS server addresses are managed by DHCP by excluding the Address parameter.

When I test compliancy using Test-DscConfiguration the command always reports $false, even when I run it directly after successful initial configurations. Get-DscConfigurationStatus reports Success for all subsequent consistency checks.

#### Verbose logs showing the problem

This is an extract from Test-DscConfiguration showing the output from the DnsServerAddress resource.

VERBOSE: [xxx]: LCM:  [ Start  Resource ]  [[DnsServerAddress]DnsDhcpEnable]
VERBOSE: [xxx]: LCM:  [ Start  Test     ]  [[DnsServerAddress]DnsDhcpEnable]
VERBOSE: [xxx]:                            [[DnsServerAddress]DnsDhcpEnable] Test-TargetResource: Checking the DNS server addresses.
VERBOSE: [xxx]:                            [[DnsServerAddress]DnsDhcpEnable] Get-DnsClientServerStaticAddress: Getting staticly assigned DNS server IPv4 address for interface alias 'MiddleEarth'.
VERBOSE: [xxx]:                            [[DnsServerAddress]DnsDhcpEnable] Get-DnsClientServerStaticAddress: Statically assigned DNS server IPv4 address for interface alias 'MiddleEarth' is not set.
**VERBOSE: [xxx]:                            [[DnsServerAddress]DnsDhcpEnable] Test-TargetResource: DNS server addresses are not correct. Expected "", actual "".**
VERBOSE: [xxx]: LCM:  [ End    Test     ]  [[DnsServerAddress]DnsDhcpEnable] False in 0.0930 seconds.
VERBOSE: [xxx]: LCM:  [ End    Resource ]  [[DnsServerAddress]DnsDhcpEnable]

When I saw 'Excpected "", actual ""' I got suspicioius.

#### Suggested solution to the issue

I have plowed through the source code for DnsServerAddress here on GitHub, and I suspect that the root cause is that the helper function Get-DnsClientServerStaticAddress returns $null when DNS server addresses are set by DHCP.

The return value from Get-DnsClientServerStaticAddress is assigned to $currentAddress in line 251-253 (in version 7.4.0.0).

```powershell
[String[]] $currentAddress = @(Get-DnsClientServerStaticAddress `
        @PSBoundParameters `
        -ErrorAction Stop)
```

If Get-DnsClientServerStaticAddress returns $null, this should be equivalent (unless I have missed something):

```powershell
[String[]] $currentAddress = @($null)
```

By executing the code above and then inspecting $currentAddress I draw the conclusion that $currentAddress is an array of string with one element that contains an empty string.

```powershell
PS > $currentAddress.Length
1
PS > $currentAddress[0] -eq ""
True
```

Since Address has been excluded in this case, I assume that $Address in Test-TargetResouce will be set to an empty array (line 231-244)

```powershell
if ($PSBoundParameters.ContainsKey('Address'))
{
    foreach ($ServerAddress in $Address)
    {
        Assert-ResourceProperty `
            -Address $ServerAddress `
            -AddressFamily $AddressFamily `
            -InterfaceAlias $InterfaceAlias
    } # foreach
}
else
{
    [String[]] $Address = @()
} # if
```

If my analysis is correct an empty array will be compared with an array with one element that is an empty string in line 256-259.

```powershell
[Boolean] $addressDifferent = (@(Compare-Object `
    -ReferenceObject $currentAddress `
    -DifferenceObject $Address `
    -SyncWindow 0).Length -gt 0)
```

And that should obvisionsly result in that $addressDifferent is set to $true, and that Test-TargetResource always returns $false.

Is it possible to change Get-DnsClientServerStaticAddress so @() is returned instead of $null when DNS server addresses are set by DHCP? Maybe this will break other resources, but if not it seems to be a solution.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)

My configuration is a partial configuration for servers with IP addresses managed by DHCP.

```powershell
Configuration NetDynIP
{
    Import-DscResource -ModuleName NetworkingDsc -ModuleVersion 7.4.0.0

    Node $AllNodes.Where{$_.NodeName -eq "$NodeName"}.NodeName
    {
        NetAdapterName MiddleEarthNetAdapter
        {
            MacAddress     = "$($Node.MACAddress)"
            NewName        = "MiddleEarth"
        }

        NetIPInterface DhcpEnable
        {
            InterfaceAlias = "MiddleEarth"
            AddressFamily  = "IPv4"
            Dhcp           = "Enabled"
            DependsOn      = "[NetAdapterName]MiddleEarthNetAdapter"
        }

        DnsServerAddress DnsDhcpEnable
        {
            InterfaceAlias = "MiddleEarth"
            AddressFamily  = "IPv4"
            DependsOn      = "[NetAdapterName]MiddleEarthNetAdapter"
        }
    }
}
```

#### The operating system the target node is running

OsName               : Microsoft Windows Server 2019 Standard
OsOperatingSystemSKU : StandardServerEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1809
WindowsBuildLabEx    : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version and build of PowerShell the target node is running

Name                           Value
----                           -----
PSVersion                      5.1.17763.1007
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.1007
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

#### Version of the DSC module that was used ('dev' if using current dev branch)

7.4.0.0

### PR DESCRIPTION
**Pull request by phbits**
#### Pull Request (PR) description
 - Simplified Set-TargetResource by removing logic to get current value. Since wildcards are not being used, the current value doesn't need to be verified because Test-TargetResource has already done the work.
 - Added error handling to write a more descriptive error when `validation=$true` and it fails.
 - Updated Verbose message strings to provide more information to ease debugging.
 - Updated common function `Get-DnsClientServerStaticAddress` to return an empty string (`@()`) rather than `$null` if DNS Servers are not specified which fixes #446.

#### This Pull Request (PR) fixes the following issues

    - Fixes #446

#### Task list

- [ ] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md in resource folder.
- [ ] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/networkingdsc/480)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Hi @phbits - I'm back on board now, so keen to get this through. The tests are failing because the unit tests are failing. Are you able to update these?

Also, could you add a CHANGELOG.MD entry for this?

**Comment by phbits** [comment]
Hi @PlagueHO! All tests are now successful. I'll wait for the Reviewable update.

**Review by PlagueHO — CHANGES_REQUESTED** [review]
Thanks @phbits - just some really minor tweaks and I'll merge.

> Reviewed 1 of 3 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/networkingdsc/480#-:-MOKGtjn-z8p2xZ2yE5x:bw6ck2f)* status: all files reviewed, 3 unresolved discussions (waiting on @phbits)

___
*[CHANGELOG.md, line 13 at r2](https://reviewable.io/reviews/dsccommunity/networkingdsc/480#-MOKFpNACnP0XGy_KK7y:-MOKFpNACnP0XGy_KK7z:bpfns22) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/9e2d7042c91cb9929b3f95d5498898768eff66c0/CHANGELOG.md#L13)):*
> ```Markdown
> 
> - DnsServerAddress
>   - Improved error handling. Fixes [Issue #446](https://github.com/dsccommunity/NetworkingDsc/issues/446)
> ```

Just for consistency, can you use the format `Improved error handling - fixes [Issue #446](https://github.com/dsccommunity/NetworkingDsc/issues/446).` and put a full stop at the end?
___
*[source/DSCResources/DSC_DnsServerAddress/DSC_DnsServerAddress.psm1, line 113 at r2](https://reviewable.io/reviews/dsccommunity/networkingdsc/480#-MOKG3K1-jg10levIfP2:-MOKG3K2Eu-vRl3Dj3L1:b-8idl0n) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/9e2d7042c91cb9929b3f95d5498898768eff66c0/source/DSCResources/DSC_DnsServerAddress/DSC_DnsServerAddress.psm1#L113)):*
> ```PowerShell
> 
>     Write-Verbose -Message ( @("$($MyInvocation.MyCommand): "
>         $($script:localizedData.ApplyingDnsServerAddressesMessage -f ($AddressFamily), ($Address -join ','), $InterfaceAlias)
> ```

Shouldn't need () around $AddressFamily.
___
*[source/DSCResources/DSC_DnsServerAddress/DSC_DnsServerAddress.psm1, line 137 at r2](https://reviewable.io/reviews/dsccommunity/networkingdsc/480#-MOKGAjp0lpQwosblyVm:-MOKGAjp0lpQwosblyVn:b54w3fu) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/9e2d7042c91cb9929b3f95d5498898768eff66c0/source/DSCResources/DSC_DnsServerAddress/DSC_DnsServerAddress.psm1#L137)):*
> ```PowerShell
>     }
> 
>     # added try/catch block to provide more feedback when
> ```

I don't think the comment block is needed.
    
___
*[source/DSCResources/DSC_DnsServerAddress/DSC_DnsServerAddress.psm1, line 224 at r2](https://reviewable.io/reviews/dsccommunity/networkingdsc/480#-MOKGb1e-PLPv6b0GCHS:-MOKGb1f6d7AMfzX8r-3:bawe941) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/9e2d7042c91cb9929b3f95d5498898768eff66c0/source/DSCResources/DSC_DnsServerAddress/DSC_DnsServerAddress.psm1#L224)):*
> ```PowerShell
>     else
>     {
>         [System.String[]] $Address = @()
> ```

fyi: good catch :grin:

**Review by phbits — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/networkingdsc/480)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @PlagueHO)

___
*[CHANGELOG.md, line 13 at r2](https://reviewable.io/reviews/dsccommunity/networkingdsc/480#-MOKFpNACnP0XGy_KK7y:-MOcN0xQ2HZvmofr6Wjt:b-896fix) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/9e2d7042c91cb9929b3f95d5498898768eff66c0/CHANGELOG.md#L13)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Just for consistency, can you use the format `Improved error handling - fixes [Issue #446](https://github.com/dsccommunity/NetworkingDsc/issues/446).` and put a full stop at the end?
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_DnsServerAddress/DSC_DnsServerAddress.psm1, line 113 at r2](https://reviewable.io/reviews/dsccommunity/networkingdsc/480#-MOKG3K1-jg10levIfP2:-MOcN3Ki-TaHlVzJH5Wu:b-896fix) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/9e2d7042c91cb9929b3f95d5498898768eff66c0/source/DSCResources/DSC_DnsServerAddress/DSC_DnsServerAddress.psm1#L113)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Shouldn't need () around $AddressFamily.
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_DnsServerAddress/DSC_DnsServerAddress.psm1, line 137 at r2](https://reviewable.io/reviews/dsccommunity/networkingdsc/480#-MOKGAjp0lpQwosblyVm:-MOcNAmi7sSJSykprvFy:b-896fix) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/9e2d7042c91cb9929b3f95d5498898768eff66c0/source/DSCResources/DSC_DnsServerAddress/DSC_DnsServerAddress.psm1#L137)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

I don't think the comment block is needed.
    
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_DnsServerAddress/DSC_DnsServerAddress.psm1, line 224 at r2](https://reviewable.io/reviews/dsccommunity/networkingdsc/480#-MOKGb1e-PLPv6b0GCHS:-MOcNDF22h3yCrFHbBNU:bgxjva7) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/9e2d7042c91cb9929b3f95d5498898768eff66c0/source/DSCResources/DSC_DnsServerAddress/DSC_DnsServerAddress.psm1#L224)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

fyi: good catch :grin:
</blockquote></details>

Thanks :smiley:

**Review by phbits — COMMENTED** [review]
Great! Just finished the edits.

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/networkingdsc/480#-:-MOcOGiH2rnkSdJiOWR9:b-ou0gqz)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @PlagueHO)

**Comment by PlagueHO** [comment]
Hi @phbits - can you resolve the conflicts on this one? Check that the changes in the CHANGELOG.md appear in the [Unreleased] section.

**Review by phbits — COMMENTED** [review]
Updated CHANGELOG.md

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/networkingdsc/480#-:-MPXEz7D9tGmaRkxNzH1:btsx9vf)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @PlagueHO)

**Comment by PlagueHO** [comment]
Hi @phbits - looks like there are still conflicts in the CHANGELOG.md

**Comment by PlagueHO** [comment]
Hi @phbits - can you resolve the conflicts on this one?

**Review by PlagueHO — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/networkingdsc/480)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by phbits** [comment]
@PlagueHO Thanks for merging the other PR! I updated CHANGELOG.md with changes from prior PRs as I figure that's the issue.

**Comment by PlagueHO** [comment]
Hi @phbits - it looks like there are some merge conflicts. Can you resolve?

**Comment by phbits** [comment]
Hi @PlagueHO! The only merge conflict I can see is for CHANGELOG.md which shows the entry for this PR. Snippet below.

```
<<<<<<< DnsServerAddress
- DnsServerAddress
  - Improved error handling - fixes [Issue #446](https://github.com/dsccommunity/NetworkingDsc/issues/446).
=======
>>>>>>> master
```

**Comment by PlagueHO** [comment]
@phbits - yep, that's the conflict that appears in the PR. Just replace the conflict block with:
```
- DnsServerAddress
  - Improved error handling - fixes [Issue #446](https://github.com/dsccommunity/NetworkingDsc/issues/446).
```

**Comment by phbits** [comment]
@PlagueHO - The content block is already present in the PR whereas that same content block is missing in master/main. Nothing to replace. 😉 

Originally there was a conflict with just having the DnsServerAddress entry. I added the other entries to changelog in this PR; making it current which is shown in [Reviewable](https://reviewable.io/reviews/dsccommunity/networkingdsc/480). Still shows conflict though focused on the [DnsServerAddress entry](https://github.com/dsccommunity/NetworkingDsc/pull/480/conflicts). If I'm not mistaken, won't the merge process resolve this? 🤔

**Comment by PlagueHO** [comment]
Unfortunately the merge won't resolve this conflict. It may be that you need to fetch the main branch again and rebase your branch onto it. But I can actually resolve this for you.

**Comment by PlagueHO** [comment]
If you pull your branch again the conflict should be resolved. But what I'd normally recommend is that a rebase is used to resolve the conflicts (rather than a merge from main).

**Review by phbits — COMMENTED** [review]
Understood. :thumbsup: I'll take that approach moving forward as I see how it would have streamlined things.

All tests are green so I believe this PR is all set to merge. :partying_face: 

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/networkingdsc/480#-:-MUP6FtE588s1gfe_qvv:b2y9c3s)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @PlagueHO)

**Review by PlagueHO — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/networkingdsc/480)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by PlagueHO — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/networkingdsc/480#-:-MUS4ZG40jQCuMfME-k-:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
