### PR TITLE
Add Code Coverage support to Build Pipeline - Fixes #491

### LINKED ISSUE #489: Update Sampler Build Tasks
Update the Sampler Build tasks as per this blog post: https://dsccommunity.org/blog/updating-sampler-github-tasks/

### LINKED ISSUE #491: Enable Code Coverage Reporting
Enable code coverage reporting as per this blog post: https://dsccommunity.org/blog/add-codecov-support-to-repository/

### PR DESCRIPTION
**Pull request by PlagueHO**
#### Pull Request (PR) description

This PR adds support for code coverage to build pipelines.

#### This Pull Request (PR) fixes the following issues

- Fixes #491 
- Fixes #489 

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md in resource folder.
- [ ] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

@johlju - would you mind reviewing this PR when you have time?

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/networkingdsc/492)

### CODE REVIEW

**Review by johlju — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/networkingdsc/492)* status: all files reviewed, 2 unresolved discussions (waiting on @PlagueHO)

___
*[azure-pipelines.yml, line 93 at r2](https://reviewable.io/reviews/dsccommunity/networkingdsc/492#-MYec6RA5rQHIjL8mbOo:-MYec6RA5rQHIjL8mbOp:b1m1q86) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/edf0706e36bb3156860dd9d508b71ad6d6c6d8a7/azure-pipelines.yml#L93)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>           - powershell: |
>               $repositoryOwner,$repositoryName = $env:BUILD_REPOSITORY_NAME -split '/'
>               echo "##vso[task.setvariable variable=RepositoryOwner;isOutput=true]$repositoryOwner"
>               echo "##vso[task.setvariable variable=RepositoryName;isOutput=true]$repositoryName"
>             name: dscBuildVariable
>             displayName: 'Set Environment Variables'
> ```
</details>


This is not needed here any longer, it is just needed in the Code_Coverage job now.
___
*[azure-pipelines.yml, line 212 at r2](https://reviewable.io/reviews/dsccommunity/networkingdsc/492#-MYecZXs-B5l0LKmtPwG:-MYecZXs-B5l0LKmtPwH:b-ycpwrv) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/edf0706e36bb3156860dd9d508b71ad6d6c6d8a7/azure-pipelines.yml#L212)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>           - powershell: |
>               $repositoryOwner,$repositoryName = $env:BUILD_REPOSITORY_NAME -split '/'
>               echo "##vso[task.setvariable variable=RepositoryOwner;isOutput=true]$repositoryOwner"
>               echo "##vso[task.setvariable variable=RepositoryName;isOutput=true]$repositoryName"
>             name: dscBuildVariable
>             displayName: 'Set Environment Variables'
> ```
</details>


This is not needed here any longer.

**Review by johlju — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/networkingdsc/492)* status: all files reviewed, 3 unresolved discussions (waiting on @PlagueHO)

___
*[azure-pipelines.yml, line 137 at r2](https://reviewable.io/reviews/dsccommunity/networkingdsc/492#-MYef0Os7P4_aSGZParE:-MYef0Os7P4_aSGZParF:bnyitus) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/edf0706e36bb3156860dd9d508b71ad6d6c6d8a7/azure-pipelines.yml#L137)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>           - pwsh: |
>               $repositoryOwner,$repositoryName = $env:BUILD_REPOSITORY_NAME -split '/'
>               echo "##vso[task.setvariable variable=RepositoryOwner;isOutput=true]$repositoryOwner"
>               echo "##vso[task.setvariable variable=RepositoryName;isOutput=true]$repositoryName"
>             name: dscBuildVariable
>             displayName: 'Set Environment Variables'
> ```
</details>


It is not needed here any longer either... It was used for `pathToSources` before to point to sources in the output folder, but it does not work when we have built modules like a common module (or DnsServerDsc that uses class-based resources).
So we can rmeove this throughout.  The variable `dscBuildVariable` is not used anywhere now.

**Review by PlagueHO — COMMENTED** [review]
This should be good to go now @johlju 

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/networkingdsc/492#-:-MYi07Y7-aIjoxoFd8rs:biu633z)* status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @johlju)

___
*[azure-pipelines.yml, line 93 at r2](https://reviewable.io/reviews/dsccommunity/networkingdsc/492#-MYec6RA5rQHIjL8mbOo:-MYi04zrCSKjvUjImKBY:b-896fix) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/edf0706e36bb3156860dd9d508b71ad6d6c6d8a7/azure-pipelines.yml#L93)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
>           - powershell: |
>               $repositoryOwner,$repositoryName = $env:BUILD_REPOSITORY_NAME -split '/'
>               echo "##vso[task.setvariable variable=RepositoryOwner;isOutput=true]$repositoryOwner"
>               echo "##vso[task.setvariable variable=RepositoryName;isOutput=true]$repositoryName"
>             name: dscBuildVariable
>             displayName: 'Set Environment Variables'
> ```

This is not needed here any longer, it is just needed in the Code_Coverage job now.
</blockquote></details>

Done.
___
*[azure-pipelines.yml, line 137 at r2](https://reviewable.io/reviews/dsccommunity/networkingdsc/492#-MYef0Os7P4_aSGZParE:-MYi05W301DE6tRSDNga:b-896fix) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/edf0706e36bb3156860dd9d508b71ad6d6c6d8a7/azure-pipelines.yml#L137)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
>           - pwsh: |
>               $repositoryOwner,$repositoryName = $env:BUILD_REPOSITORY_NAME -split '/'
>               echo "##vso[task.setvariable variable=RepositoryOwner;isOutput=true]$repositoryOwner"
>               echo "##vso[task.setvariable variable=RepositoryName;isOutput=true]$repositoryName"
>             name: dscBuildVariable
>             displayName: 'Set Environment Variables'
> ```

It is not needed here any longer either... It was used for `pathToSources` before to point to sources in the output folder, but it does not work when we have built modules like a common module (or DnsServerDsc that uses class-based resources).
So we can rmeove this throughout.  The variable `dscBuildVariable` is not used anywhere now.
</blockquote></details>

Done.
___
*[azure-pipelines.yml, line 212 at r2](https://reviewable.io/reviews/dsccommunity/networkingdsc/492#-MYecZXs-B5l0LKmtPwG:-MYi06739Bm1yCrpySV_:b-896fix) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/edf0706e36bb3156860dd9d508b71ad6d6c6d8a7/azure-pipelines.yml#L212)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
>           - powershell: |
>               $repositoryOwner,$repositoryName = $env:BUILD_REPOSITORY_NAME -split '/'
>               echo "##vso[task.setvariable variable=RepositoryOwner;isOutput=true]$repositoryOwner"
>               echo "##vso[task.setvariable variable=RepositoryName;isOutput=true]$repositoryName"
>             name: dscBuildVariable
>             displayName: 'Set Environment Variables'
> ```

This is not needed here any longer.
</blockquote></details>

Done.

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/networkingdsc/492#-:-MYo7cXdCHUhWpNoeJu1:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @johlju)

**Review by johlju — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/networkingdsc/492)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PlagueHO)

**Pull request merged**
