### PR TITLE
DnsServerAddress: Making Get/Test less suicidal.

### PR DESCRIPTION
**Pull request by bielawb**
#### Pull Request (PR) description
I noticed that DnsServerAddress will throw if/when interface with a given alias is not found, resulting in whole `Test-DscResource` / `Get-DscResource` failing, making it impossible to fix what *else* is not in desired state.

#### Task list

- [ ] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md in resource folder.
- [ ] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/networkingdsc/420)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Hi @bielawb - sorry about the delay reviewing this one. Can you fix the tests so that they pass?

Also, are you able to ensure there is test coverage of the behavior when the adapter does not exist? Finally, I'd also suggest using Write-Warning, rather than Write-Verbose when an adapter does not exist as this is a condition that should be considered an undesired/unusual situation that should be bought to a users attention.

**Comment by bielawb** [comment]
I guess I fixed all the issues (and adding tests proved to be, as usual, good idea - found few bugs in the process).

**Comment by PlagueHO** [comment]
Hi @bielawb - are you still working on this one?

**Comment by PlagueHO** [comment]
Closing because abandoned

**Pull request closed without merging**
