### PR TITLE
NetAdapterLso: Fixes #475, Protocol Key field & config overlap with NetAdapterAdvancedProperty

### LINKED ISSUE #475: NetAdapterLso - limit to only Protocol = V1IPv4
My DSC config is:

````
Configuration NetAdapterLsoTest
{
    Import-DscResource -Module NetworkingDsc
    Node localhost
    {
        NetAdapterLso Ethernet_V1IPv4_NetAdapterLso
        {
            Name     = 'Ethernet'
            Protocol = 'V1IPv4'
            State    = $false
        }
        NetAdapterLso Ethernet_IPv4_NetAdapterLso
        {
            Name     = 'Ethernet'
            Protocol = 'IPv4'
            State    = $false
        }
        NetAdapterLso Ethernet_IPv6_NetAdapterLso
        {
            Name     = 'Ethernet'
            Protocol = 'IPv6'
            State    = $false
        }
    }
}

. NetAdapterLsoTest -OutputPath C:\DscTest\NetAdapterLsoTest -Verbose
````

Running the above file creates the following error:

````
Test-ConflictingResources : A conflict was detected between resources '[NetAdapterLso]Ethernet_V1IPv4_NetAdapterLso (C:\DscTest\NetAdapterLsoTest.ps1::7::9::NetAdapterLso)' and '[NetAdapterLso]Ethernet_IPv4_NetAdapterLso
(C:\DscTest\NetAdapterLsoTest.ps1::14::9::NetAdapterLso)' in node 'localhost'. Resources have identical key properties but there are differences in the following non-key properties: 'State;Protocol'. Values 'NULL;V1IPv4' don't match values 'True;IPv4'. Please update
these property values so that they are identical in both cases.
At line:289 char:9
+         Test-ConflictingResources $keywordName $canonicalizedValue $k ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Write-Error], InvalidOperationException
    + FullyQualifiedErrorId : ConflictingDuplicateResource,Test-ConflictingResources
Test-ConflictingResources : A conflict was detected between resources '[NetAdapterLso]Ethernet_V1IPv4_NetAdapterLso (C:\DscTest\NetAdapterLsoTest.ps1::7::9::NetAdapterLso)' and '[NetAdapterLso]Ethernet_IPv6_NetAdapterLso
(C:\DscTest\NetAdapterLsoTest.ps1::20::9::NetAdapterLso)' in node 'localhost'. Resources have identical key properties but there are differences in the following non-key properties: 'State;Protocol'. Values 'NULL;V1IPv4' don't match values 'True;IPv6'. Please update
these property values so that they are identical in both cases.
At line:289 char:9
+         Test-ConflictingResources $keywordName $canonicalizedValue $k ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Write-Error], InvalidOperationException
    + FullyQualifiedErrorId : ConflictingDuplicateResource,Test-ConflictingResources
Test-ConflictingResources : A conflict was detected between resources '[NetAdapterLso]Ethernet_IPv4_NetAdapterLso (C:\DscTest\NetAdapterLsoTest.ps1::14::9::NetAdapterLso)' and '[NetAdapterLso]Ethernet_IPv6_NetAdapterLso
(C:\DscTest\NetAdapterLsoTest.ps1::20::9::NetAdapterLso)' in node 'localhost'. Resources have identical key properties but there are differences in the following non-key properties: 'Protocol'. Values 'IPv4' don't match values 'IPv6'. Please update these property
values so that they are identical in both cases.
At line:289 char:9
+         Test-ConflictingResources $keywordName $canonicalizedValue $k ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Write-Error], InvalidOperationException
    + FullyQualifiedErrorId : ConflictingDuplicateResource,Test-ConflictingResources
Compilation errors occurred while processing configuration 'NetAdapterLsoTest'. Please review the errors reported in error stream and modify your configuration code appropriately.
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psm1:3917 char:5
+     throw $ErrorRecord
+     ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (NetAdapterLsoTest:String) [], InvalidOperationException
    + FullyQualifiedErrorId : FailToProcessConfiguration
````

It seems an adapter can only be specified once using `NetAdapterLso` which restricts the configuration to just one protocol. Instead of fixing `NetAdapterLso` to accept multiple entries for a single adapter, I propose using `NetAdapterLso` for only `V1IPv4`. Then use `NetAdapterAdvancedProperty` for the other two. The following table shows how these values compare.

| NetAdapterLso | NetAdapterAdvancedProperty |
| -------------------- | ---------------------------------------- |
| V1IPv4 | ?? |
| IPv4 | *LsoV2IPv4 |
| IPv6 | *LsoV2IPv6 |

#### The operating system the target node is running
```
PS C:\PowerShell> Get-ComputerInfo -Property @( 'OsName','OsOperatingSystemSKU','OSArchitecture','WindowsVersion','WindowsBuildLabEx','OsLanguage','OsMuiLanguages')


OsName               : Microsoft Windows Server 2019 Datacenter Evaluation
OsOperatingSystemSKU : 80
OsArchitecture       : 64-bit
WindowsVersion       : 1809
WindowsBuildLabEx    : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

```

#### Version and build of PowerShell the target node is running
```
PS C:\PowerShell> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17763.316
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.316
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### PR DESCRIPTION
**Pull request by phbits**
#### Pull Request (PR) description

- Designated the Protocol field as a Key in the mof allowing multiple protocol configurations for a single interface.
- Updated NetAdapterLso wiki showing configuration overlap with NetAdapterAdvancedProperty.
- Updated NetAdapterAdvancedProperty wiki showing configuration overlap with NetAdapterLso

#### This Pull Request (PR) fixes the following issues

    - Fixes #475

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [x] Resource documentation added/updated in README.md in resource folder.
- [ ] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/networkingdsc/481)

### CODE REVIEW

**Review by PlagueHO — CHANGES_REQUESTED** [review]
Just a minor tweak needed.

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/networkingdsc/481#-:-MOKIeZ-7btsljRC9W_X:bnil0z0)* status: all files reviewed, 1 unresolved discussion (waiting on @phbits)

___
*[CHANGELOG.md, line 15 at r1](https://reviewable.io/reviews/dsccommunity/networkingdsc/481#-MOKIHhg4YD1p99RBnKb:-MOKIHhg4YD1p99RBnKc:bfkccyi) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/6cae22ccaafa050495f41f98f65a7c4b2636d724/CHANGELOG.md#L15)):*
> ```Markdown
>   - Protocol now a key field allowing multiple protocol configurations for a single network adapter.
>   - Updated wiki documentation showing configuration overlap with NetAdapterAdvancedProperty.
>   - Fixes [Issue #475](https://github.com/dsccommunity/NetworkingDsc/issues/475)
> ```

Can you indicate which of the above lines fixes #475? Or is it all of them? If it is multiple, add the ` - fixes ` to each line.

**Review by phbits — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/networkingdsc/481)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @PlagueHO)

___
*[CHANGELOG.md, line 15 at r1](https://reviewable.io/reviews/dsccommunity/networkingdsc/481#-MOKIHhg4YD1p99RBnKb:-MOO1czG6pvt_O-ukFEQ:b-896fix) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/6cae22ccaafa050495f41f98f65a7c4b2636d724/CHANGELOG.md#L15)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you indicate which of the above lines fixes #475? Or is it all of them? If it is multiple, add the ` - fixes ` to each line.
</blockquote></details>

Done.

**Comment by phbits** [comment]
@PlagueHO - Thanks for the reviews! Taking care of the low hanging fruit first.

**Review by PlagueHO — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/networkingdsc/481#-:-MPR0Ptg9yEHhWpXo287:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
