### PR TITLE
Update to latest CI pipeline pattern - Fixes #528

### LINKED ISSUE #528: Update Pipeline Files to Latest DSC Community and Sampler pattern
To fix current build failures need to update the pipeline to use the latest patterns.

### PR DESCRIPTION
**Pull request by PlagueHO**
#### Pull Request (PR) description

This PR updates the pipeline and supporting files to the latest DSC Community pattern. It also updates the build and HQRM VM images to run on `windows-latest`

#### This Pull Request (PR) fixes the following issues

- Fixes #528 

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).

Remaining N/A

- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

- - -
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/NetworkingDsc/529)

### CODE REVIEW

**Comment by PlagueHO** [comment]
@johlju - would you mind reviewing when you get a chance? This is just a pipeline update and will unblock #526 and #523

**Comment by PlagueHO** [comment]
Not sure why LoopbackAdapter package isn't being installed/found....

/AzurePipelines run

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 3 of 9 files at r1, 1 of 2 files at r2, 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/NetworkingDsc/529#-:-NznuBpO1HFud_5DQAEy:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @PlagueHO)

**Pull request merged**
