### PR TITLE
DNSServerAddress: Fixed comparison error when no DNS server is set. DSC Resource returns always false

### LINKED ISSUE #211: xDnsServerAddress does not allow clearing of primary/secondary DNS Address
Address has a ValidateNotNullOrEmpty attribute however it's a valid operation to clear it.
If using DHCP then the manual address would be set back to automatic (just like the GUI).
If using a static IP, then the manual addresses would be cleared.

### PR DESCRIPTION
**Pull request by rcarboneras**
#### DNSServerAddress: Fixes #211  resource does not check well DNS Server list is empty, neither clears them.

The parameter Address should do the trick 

  .PARAMETER Address
       The desired DNS Server address(es). Exclude to enable DHCP.

but in module **DSC_DnsServerAddress.psm1**, when the machine has DNS set to automatic, the following lines return an array with one $null object as member:  $currentAddress = **@($null)**

253    [String[]] $currentAddress = @(Get-DnsClientServerStaticAddress `
254       @PSBoundParameters `
255        -ErrorAction Stop)

When you don't specify an $Address parameter in the DSC resource, the $Address variable is set to an array with NO members: @(), in this lines:

243    else
244    {
245        [String[]] **$Address = @()**
246    } # if

thus, this comparison is always false ( **@()** is not equal to **@($null)** ):

258    [Boolean] **$addressDifferent** = (@(Compare-Object `
259            -ReferenceObject $currentAddress `
260            -DifferenceObject $Address `
261            -SyncWindow 0).Length -gt 0)

This is easilly fixed setting $Addess to @($null)

243    else
244    {
245        [String[]] **$Address = @($null)**
246    } # if

Tested and working in my environment :)

#### This Pull Request (PR) fixes the following issues
- Fixes #211

#### Task list
- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md in resource folder.
- [ ] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/networkingdsc/482)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Hi @rcarboneras - can you fix the merge conflicts and I'll review?

**Comment by phbits** [comment]
@rcarboneras, @PlagueHO 

Using this approach produces the following:

```powershell
PS C:\> [System.String[]] $One = @()
PS C:\> [System.String[]] $Two = @($null)
PS C:\> $One.Count
0
PS C:\> $Two.Count
1
```

This will create problems since `Get-TargetResource` will use a value like `$One` whereas `Test-TargetResource` will use the `$Two` value. This will cause `Set-TargetResource` to run every time since `$One -ne $Two`.

**Comment by rcarboneras** [comment]
@phbits  

> @rcarboneras, @PlagueHO
> 
> Using this approach produces the following:
> 
> ```powershell
> PS C:\> [System.String[]] $One = @()
> PS C:\> [System.String[]] $Two = @($null)
> PS C:\> $One.Count
> 0
> PS C:\> $Two.Count
> 1
> ```
> 
> This will create problems since `Get-TargetResource` will use a value like `$One` whereas `Test-TargetResource` will use the `$Two` value. This will cause `Set-TargetResource` to run every time since `$One -ne $Two`.

In my tests it works. You never call the Get-Targetresource function when testing a configuration, so Test-Targetresource returns $true and Set-Targetresource is never executed :)

**Comment by phbits** [comment]
@rcarboneras - [PR #480](https://github.com/dsccommunity/NetworkingDsc/pull/480) was recently merged which I believe addresses the issue you're trying to solve. Have you tried the latest build of NetworkingDSC?

**Comment by rcarboneras** [comment]
@phbits @PlagueHO 
I've tried with the latest version. Now if looks cleaner :).

Nevertheless, it has the same issue in the Test-TargetResource function than before, and it doesn'twork for me

It tries to compare
[System.String[]] $Address = @()

With 
[String[]] $currentAddress = @(Get-DnsClientServerStaticAddress `
        @PSBoundParameters `
        -ErrorAction Stop)
        
 And that is the same as compare
@() 
 with
 @($null)
 
 which returns a $false always, even when no Address parameter is passed to the function.
 
 An easy fix is changing this line 
 [System.String[]] $Address = @()

for this one

 [System.String[]] $Address = @($null)
 
I will open a new PR for this.

**Pull request closed without merging**
