### PR TITLE
Common: Added Test-IPAddress function

### LINKED ISSUE #408: Refactor IP Address Validation into Common Function
DefaultGatewayAddress, DnsServerAddress, IPAddress, Route all validate an IP address is valid. The code is duplicated in each of these modules. It should be refactored into the Common module.

### PR DESCRIPTION
**Pull request by valainisgt**
#### Pull Request (PR) description
Refactored code from DefaultGatewayAddress, DnsServerAddress, IPAddress, and Route resources to use a common function for validating an IP Address.

#### This Pull Request (PR) fixes the following issues
Fixes #408 

#### Task list
- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md in resource folder.
- [ ] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/networkingdsc/449)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Hi @valainisgt - awesome stuff! Thank you for submitting this. Looks like there a few tests to fix up, nothing major:
1. HQRM validation: There are some localization strings that are no longer used and so need to be removed: https://github.com/dsccommunity/NetworkingDsc/pull/449/checks?check_run_id=618477429
2. Unit Tests: It looks like the tests are failing that validated what would happen when an invalid IP Address is being used: https://dev.azure.com/dsccommunity/NetworkingDsc/_build/results?buildId=1600&view=logs&jobId=158455ef-2db5-56fd-6022-83ded799e050&j=158455ef-2db5-56fd-6022-83ded799e050&t=b737ddad-5217-50db-260a-b6e0dd548ea1

Let me know if you need a hand looking into these.

**Comment by PlagueHO** [comment]
Thanks for fixing tests @valainisgt - I'll get onto the review tonight. This function may also be a candidate for moving out into the wider DscResource.Common module to share among multiple resources. Tagging @johlju.

**Comment by johlju** [comment]
This is cool! I was just looking for a helper function just like this one. :)

**Comment by johlju** [comment]
@valainisgt would like to submit the helper function `Assert-IPAddress` to the [DscResource.Common](https://github.com/dsccommunity/DscResource.Common) module? I'm in need of a function like this in SqlServerDsc for a resource I'm currently coding.

**Comment by valainisgt** [comment]
@johlju absolutely.  I will get a you a PR soon.

**Comment by PlagueHO** [comment]
Hi @valainisgt - It looks like the unit tests on WS2019 are failing. I'm not sure why however, so I'm kicking them off again.

**Comment by PlagueHO** [comment]
@johlju - can you tick off your approval on this one?

**Comment by johlju** [comment]
@PlagueHO signed off and merged.

@valainisgt Thank you for this! Awesome work on this as well, add again thanks for adding it to DscResource.Common.

**Pull request merged**
