### PR TITLE
InterfaceMetric: Configure a static metric for an IPv4 Interface

### LINKED ISSUE #391: NetIPInterface: AutomaticMetric set to disabled dosent work
#### Details of the scenario you tried and the problem that is occurring
I needed to set metric of interface (not route) to highest value possible. So i needed to something like but in DSC.
```
Set-NetIPInterface -InterfaceIndex 6 -AutomaticMetric Disabled -InterfaceMetric 254
```

#### Verbose logs showing the problem
```
VERBOSE: [Server01]: LCM:  [ End    Resource ]  [[NetAdapterName]NameToISCSI]
VERBOSE: [Server01]: LCM:  [ Start  Resource ]  [[NetIPInterface]DisableDhcp]
VERBOSE: [Server01]: LCM:  [ Start  Test     ]  [[NetIPInterface]DisableDhcp]
VERBOSE: [Server01]:                            [[NetIPInterface]DisableDhcp] Test-TargetResource: Checking settings on net IP interface for alias 'iSCSI' and address family 'IPv4'.
VERBOSE: [Server01]:                            [[NetIPInterface]DisableDhcp] Get-NetworkIPInterface: Getting settings for net IP interface for alias 'iSCSI' and address family 'IPv4'.
VERBOSE: [Server01]:                            [[NetIPInterface]DisableDhcp] Test-TargetResource: The property 'AutomaticMetric' value 'Enabled' does not match the desired value 'Disabled'.
VERBOSE: [Server01]: LCM:  [ End    Test     ]  [[NetIPInterface]DisableDhcp]  in 0.0160 seconds.
VERBOSE: [Server01]: LCM:  [ Start  Set      ]  [[NetIPInterface]DisableDhcp]
VERBOSE: [Server01]:                            [[NetIPInterface]DisableDhcp] Set-TargetResource: Applying settings to net IP interface for alias 'iSCSI' and address family 'IPv4'.
VERBOSE: [Server01]:                            [[NetIPInterface]DisableDhcp] Get-NetworkIPInterface: Getting settings for net IP interface for alias 'iSCSI' and address family 'IPv4'.
VERBOSE: [Server01]:                            [[NetIPInterface]DisableDhcp] Set-TargetResource: Setting Net IP interface for alias 'iSCSI' and address family 'IPv4' parameter 'AutomaticMetric' to 'Disabled'.
The parameter is incorrect.
    + CategoryInfo          : InvalidArgument: (MSFT_NetIPInter...ystemName = ""):) [], CimException
    + FullyQualifiedErrorId : Windows System Error 87,Set-NetIPInterface
    + PSComputerName        : localhost
 
VERBOSE: [Server01]: LCM:  [ End    Set      ]  [[NetIPInterface]DisableDhcp]  in 0.5160 seconds.
The PowerShell DSC resource '[NetIPInterface]DisableDhcp' with SourceInfo 'C:\GitHub\WorkScripts\DSCiSCSIConfiguration.ps1::21::9::NetIPInterface' threw one or more non-terminating errors while running the Set-TargetResource functionality. These errors are logged to the ETW channel called 
Microsoft-Windows-DSC/Operational. Refer to this channel for more details.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : localhost
 
VERBOSE: [Server01]: LCM:  [ Start  Resource ]  [[IPAddress]NewIPv4Address]
```
#### Suggested solution to the issue
As you are ussing command Set-NetIPInterface when setting -AutomaticMetric to Disabled, there needs to be also specified parameter -InterfaceMetric.

I would like to have option in NetIPInterface to set InterfaceMetric directly. I will change this resource to set metric to 254 value when disabling auto metric, but its just my workaround.


#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```
    NetIPInterface DisableDhcp
        {
            InterfaceAlias  = 'iSCSI'
            AddressFamily   = 'IPv4'
            AutomaticMetric = 'Disabled'
        }
```

#### The operating system the target node is running
```
OsName               : Microsoft Windows Server 2016 Standard
OsOperatingSystemSKU : StandardServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 14393.2724.amd64fre.rs1_release.181231-1751
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
```
#### Version and build of PowerShell the target node is running
```
Name                           Value                                                                                                                                                                                                                                                                              
----                           -----                                                                                                                                                                                                                                                                              
PSVersion                      5.1.14393.2636                                                                                                                                                                                                                                                                     
PSEdition                      Desktop                                                                                                                                                                                                                                                                            
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                                                                                                                            
BuildVersion                   10.0.14393.2636                                                                                                                                                                                                                                                                    
CLRVersion                     4.0.30319.42000                                                                                                                                                                                                                                                                    
WSManStackVersion              3.0                                                                                                                                                                                                                                                                                
PSRemotingProtocolVersion      2.3                                                                                                                                                                                                                                                                                
SerializationVersion           1.1.0.1    
```
#### Version of the DSC module that was used ('dev' if using current dev branch)
```
Name              : NetworkingDsc
Path              : C:\Program Files\WindowsPowerShell\Modules\NetworkingDsc\7.1.0.0\NetworkingDsc.psd1
Description       : Module with DSC Resources for Networking area
ModuleType        : Manifest
Version           : 7.1.0.0
```

### LINKED ISSUE #473: interfaceMetric: Configure static metric for an IPv4 interface
### Description
Add a resource to statically configure an IPv4 interface with a metic value.

### Proposed properties
InterfaceMetric

### Special considerations or limitations
None.

### PR DESCRIPTION
**Pull request by cohdjn**
#### Pull Request (PR) description
Adds InterfaceMetric to NetIPInterface to statically configure a metric on an IPv4 interface.  I need this for multi-homed computers to give preference to one interface over another.

#### This Pull Request (PR) fixes the following issues

- Fixes #391 
- Fixes #473 

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [x] Resource documentation added/updated in README.md in resource folder.
- [x] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/networkingdsc/472)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Thanks @cohdjn - will get onto the review tomorrow

**Review by PlagueHO — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/networkingdsc/472)* status: all files reviewed, 2 unresolved discussions (waiting on @cohdjn)

___
*[CHANGELOG.md, line 16 at r1](https://reviewable.io/reviews/dsccommunity/networkingdsc/472#-MIuCF6s0YTVTlSsQGGR:-MIuCF6t8BT0iraSgSBt:b2jvuur) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/bc0a64e7c0b2da13eb202f5885f0a37539f17e13/CHANGELOG.md#L16)):*
> ```Markdown
> 
> - NetIPInterface
>   - Added `InterfaceMetric` parameter.
> ```

Can you add link to issue - e.g.
```text
 - Added `InterfaceMetric` parameter - fixes [Issue #473](https://github.com/PowerShell/xNetworking/issues/473).
```
___
*[source/DSCResources/DSC_NetIPInterface/DSC_NetIPInterface.psm1, line 433 at r1](https://reviewable.io/reviews/dsccommunity/networkingdsc/472#-MIucSytCUbjDORwxV32:-MIucSyuDPc-YFPF2_ur:b-aqgrwh) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/bc0a64e7c0b2da13eb202f5885f0a37539f17e13/source/DSCResources/DSC_NetIPInterface/DSC_NetIPInterface.psm1#L433)):*
> ```PowerShell
>         [Parameter()]
>         [System.UInt32]
>         $InterfaceMetric
> ```

If `InterfaceMetric` is specified, will `AutomaticMetric` be automatically set to 'Disabled'? If that is the case, is the reverse true? My thinking here is that if I have an adapter that currently has `InterfaceMetric` specified and `AutomaticMetric` is set to 'Disabled' but the desired state should be `AutomaticMetric` is 'Enabled' then how would this be set?

I'm wondering if we need to expose the `AutomaticMetric` parameter as well? What do you think?

**Comment by cohdjn** [comment]
I added the issue link to the CHANGELOG.md.

So here's the default state:

```powershell
Get-NetIPInterface | Select-Object ifIndex,InterfaceAlias,InterfaceMetric,AutomaticMetric

ifIndex InterfaceAlias              InterfaceMetric AutomaticMetric
------- --------------              --------------- ---------------
      4 Ethernet                                 15         Enabled
      1 Loopback Pseudo-Interface 1              75         Enabled
      4 Ethernet                                 15         Enabled
      1 Loopback Pseudo-Interface 1              75         Enabled
```

If I issue the following nonsense command, this is what happens:

```powershell
Set-NetIPInterface -InterfaceIndex 4 -AddressFamily IPv4 -AutomaticMetric Enabled -InterfaceMetric 20

Get-NetIPInterface | Select-Object ifIndex,InterfaceAlias,InterfaceMetric,AutomaticMetric

ifIndex InterfaceAlias              InterfaceMetric AutomaticMetric
------- --------------              --------------- ---------------
      4 Ethernet                                 15         Enabled
      1 Loopback Pseudo-Interface 1              75         Enabled
      4 Ethernet                                 20        Disabled
      1 Loopback Pseudo-Interface 1              75         Enabled
```
Notice I explicitly enabled `AutomaticMetric` __and__ specified `InterfaceMetric` which resulted in PowerShell ignoring the `AutomaticMetric` altogether.  Guessing Microsoft gives preference to the interface metric over the automatic metric setting and adjusts accordingly?

I suppose there's 2 ways to go here.  We could have the module throw() if there are conflicting settings which strikes me as pretty ugly.  Or we could call out something in the documentation saying if you specify a value for `InterfaceMetric` it implies `AutomaticMetric` is disabled by default.  I think this is the better road to take since that appears to be how PowerShell handles it anyway.

`AutomaticMetric` is already exposed in the module.  Maybe I missed something or didn't understand what you were trying to bring to my atttention?

**Comment by PlagueHO** [comment]
Hi @cohdjn - what I'm thinking though is that how would I set the state to `-AutomaticMetric Enabled` based on the currently exposed parameters.

The resource could assume that if `InterfaceMetric` parameter is not specified then `AutomaticMetric` should be set to `Disabled`, but that is risky DSC resource behavior- because omitting a parameter usually indicates the value should be ignored - not that a value should be set/unset.

There should always be a way to explicitly set the resource to any valid combination of values. However, only some of these combinations will be valid as you point out. So the questions I have:
1. Do we expose the `AutomaticMetric` parameter? My feeling is yes, because otherwise there is no way to set `AutomaticMetric` to `Enabled` without making an assumption (that omitting `InterfaceMetric` means you want to set `AutomaticMetric` to `Enabled`)
2. Do we detect the invalid conditions and throw an error or do we simply document the combination and leave it up to the user's knowledge. I'm OK either way here as we've done both before. Some resources contain a generic function `Assert-ResourceProperty` that is used to check the resource property combination is valid.

**Comment by cohdjn** [comment]
Hey there @PlagueHO - I think we're missing each other on the `AutomaticMetric` parameter.  `AutomaticMetric` is already an exposed DSC resource in this module and can be set to either `Enabled` or `Disabled`.  For example:

```powershell
        NetIPInterface EthernetMetric
        {
            InterfaceAlias  = 'Ethernet'
            AddressFamily   = 'IPv4'
            AutomaticMetric = 'Disabled'
            InterfaceMetric = 20
        }

        NetIPInterface Ethernet2Metric
        {
            InterfaceAlias  = 'Ethernet 2'
            AddressFamily   = 'IPv4'
            AutomaticMetric = 'Enabled'
            InterfaceMetric = 20
        }
```

These resource definitions are functionally equivalent because PowerShell will essentially ignore `AutomaticMetric` in favor of the statically configured a value for `InterfaceMetric`.  I think the "right" answer is to call out the combination in documentation.  The behavior I showed before is how PowerShell does it so it would make sense that the DSC resource use the same behavior.

**Comment by PlagueHO** [comment]
Doh!!! Haha I'm sorry- you are right. I should have checked- just assumed I hadn't exposed it. So yep, I'm happy to just note the combination in the README.md for the resource.

**Comment by cohdjn** [comment]
Awesome!  Anything else you need from me at this point?

**Review by PlagueHO — APPROVED** [review]
Nope - once you've added the entry to the README.md I'll merge. Thanks again!

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/networkingdsc/472#-:-MJ3CoxE98nqH1e2ytRh:b-did5ym)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by cohdjn** [comment]
Which README.md do you want me to make the additions to?  The main one at the top of the hierarchy or the one under `NetIPInterface`?

**Comment by PlagueHO** [comment]
The one under `NetIPInterface` - just add a section for ## Known Issues. Thanks again

**Comment by cohdjn** [comment]
Just pushed the updated `README.md` to the PR.  This should close #473 and looking around might resolve #391 too?

**Review by PlagueHO — APPROVED** [review]
Hi @cohdjn - can you check the push occurred? The README.md change hasn't showed up. And yes, I think you're right about #391.

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/networkingdsc/472#-:-MJDn_nn6DHVerGNQWEU:bd7h8i2)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by cohdjn** [comment]
That's weird.  The push didn't go through on my side.  I just pushed it and it looks better now.

**Review by PlagueHO — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/networkingdsc/472)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by PlagueHO — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/networkingdsc/472)* status: all files reviewed, 1 unresolved discussion (waiting on @cohdjn)

___
*[source/DSCResources/DSC_NetIPInterface/README.MD, line 7 at r3](https://reviewable.io/reviews/dsccommunity/networkingdsc/472#-MJQXu1PAkDQIr9ZfK36:-MJQXu1PAkDQIr9ZfK37:b-bdt02q) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/5bcc02c4164e1f832d8fbe9629ec84f3483c14dd/source/DSCResources/DSC_NetIPInterface/README.MD#L7)):*
> ```
> ## Known Issues
> 
> - If you define a value for `InterfaceMetric`, the `AutomaticMetric` setting is ignored.  PowerShell ignores `AutomaticMetric` when you use both arguments with the   `Set-NetIPInterface` cmdlet.
> ```

Minor nit pick: Can you reduce line length to < 80 chars (around end of sentence) and remove double spaces?

**Comment by cohdjn** [comment]
Minor nit pick picked.  :)

**Review by PlagueHO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/networkingdsc/472)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @cohdjn and @PlagueHO)

___
*[source/DSCResources/DSC_NetIPInterface/README.MD, line 7 at r3](https://reviewable.io/reviews/dsccommunity/networkingdsc/472#-MJQXu1PAkDQIr9ZfK36:-MJVAxVBCJZT-63XVzkC:bohlyll) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/5bcc02c4164e1f832d8fbe9629ec84f3483c14dd/source/DSCResources/DSC_NetIPInterface/README.MD#L7)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Minor nit pick: Can you reduce line length to < 80 chars (around end of sentence) and remove double spaces?
</blockquote></details>

Doh - seems one of the double spaces turned to tipple and the line is still wrapping :grin:

**Review by PlagueHO — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/networkingdsc/472)* status: all files reviewed, 1 unresolved discussion (waiting on @cohdjn)

___
*[source/DSCResources/DSC_NetIPInterface/README.MD, line 9 at r4](https://reviewable.io/reviews/dsccommunity/networkingdsc/472#-MJVBAbc6YJg6b_rN3Em:-MJVBAbc6YJg6b_rN3En:bxk3pwn) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/69446996a0054fee9581152decd7cfc1442130c7/source/DSCResources/DSC_NetIPInterface/README.MD#L9)):*
> ```
> - If you define a value for `InterfaceMetric`, the `AutomaticMetric`
>  setting is ignored. PowerShell ignores `AutomaticMetric` when you
>  use both arguments with the   `Set-NetIPInterface` cmdlet.
> ```

Sorry- correction - it is just this like that is triple spaced :) I know it is such a nitpick :cry:

**Comment by cohdjn** [comment]
It's all good!  More nits picked!  :)

**Review by PlagueHO — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/networkingdsc/472)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by PlagueHO — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/networkingdsc/472#-:-MJYMDq1DMjlv-IlqCTZ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
